name = "poxyip-table-worker"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2025-06-17"

[observability]
enabled = false

[vars]
CSV_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt"
